/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h> 


#include "stm32h7xx.h"
#include "system_stm32h7xx.h"

/* Check for FPU usage, defines are done by compiler */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  //__HAL_RCC_SYSCFG_CLK_ENABLE();

  // Init MPU and system clock
  SystemCoreClockUpdate();

  // Cache initialization
  SCB_EnableDCache();
  SCB_EnableICache();

  // Dereferencing a null pointer to trigger a hard fault
  //uint32_t *null_ptr = (uint32_t *)0x0;
  //*null_ptr = 0x1;

  /* Loop forever */
	for(;;)
  {
    printf("In a loop!");
  }
}
